using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;

public class PlayerController : MonoBehaviour
{
    // -------------------------------------------------------
    /// <summary>
    /// ï¿½Xï¿½eï¿½[ï¿½^ï¿½X.
    /// </summary>
    // -------------------------------------------------------
    [System.Serializable]
    public class Status
    {
        // ï¿½Ì—ï¿½.
        public int Hp = 10;
        // ï¿½Uï¿½ï¿½ï¿½ï¿½.
        public int Power = 1;
    }

    // ï¿½Uï¿½ï¿½Hitï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ColliderCall.
    [SerializeField] ColliderCallReceiver attackHitCall = null;
    // ï¿½ï¿½{ï¿½Xï¿½eï¿½[ï¿½^ï¿½X.
    [SerializeField] Status DefaultStatus = new Status();
    // ï¿½ï¿½ï¿½İ‚ÌƒXï¿½eï¿½[ï¿½^ï¿½X.
    public Status CurrentStatus = new Status();

    // ï¿½Uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½pï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½g.
    [SerializeField] GameObject attackHit = null;
    // ï¿½İ’uï¿½ï¿½ï¿½ï¿½pColliderCall.
    [SerializeField] ColliderCallReceiver footColliderCall = null;
    // ï¿½^ï¿½bï¿½`ï¿½}ï¿½[ï¿½Jï¿½[.
    [SerializeField] GameObject touchMarker = null;
    // ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½.
    [SerializeField] float jumpPower = 20f;

    // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Rï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½[.
    [SerializeField] PlayerCameraController cameraController = null;

    // ï¿½ï¿½ï¿½gï¿½ÌƒRï¿½ï¿½ï¿½Cï¿½_ï¿½[.
    [SerializeField] Collider myCollider = null;
    // ï¿½Uï¿½ï¿½ï¿½ï¿½Hï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½Ìƒpï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½vï¿½ï¿½ï¿½nï¿½u.
    [SerializeField] GameObject hitParticlePrefab = null;
    // ï¿½pï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ÛŠÇ—pï¿½ï¿½ï¿½Xï¿½g.
    List<GameObject> particleObjectList = new List<GameObject>();

    //! HPï¿½oï¿½[ï¿½ÌƒXï¿½ï¿½ï¿½Cï¿½_ï¿½[.
    [SerializeField] Slider hpBar = null;

    //! ï¿½Qï¿½[ï¿½ï¿½ï¿½Iï¿½[ï¿½oï¿½[ï¿½ï¿½ï¿½Cï¿½xï¿½ï¿½ï¿½g.
    public UnityEvent GameOverEvent = new UnityEvent();
    // ï¿½Jï¿½nï¿½ï¿½ï¿½Ê’u.
    Vector3 startPosition = new Vector3();
    // ï¿½Jï¿½nï¿½ï¿½ï¿½pï¿½x.
    Quaternion startRotation = new Quaternion();

    // ï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½^ï¿½[.
    Animator animator = null;
    // ï¿½ï¿½ï¿½Wï¿½bï¿½hï¿½{ï¿½fï¿½B.
    Rigidbody rigid = null;
    //! ï¿½Uï¿½ï¿½ï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½O.
    bool isAttack = false;
    // ï¿½Ú’nï¿½tï¿½ï¿½ï¿½O.
    bool isGround = false;

    // PCï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½.
    float horizontalKeyInput = 0;
    // PCï¿½Lï¿½[ï¿½cï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½.
    float verticalKeyInput = 0;

    bool isTouch = false;

    // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½^ï¿½bï¿½`ï¿½Xï¿½^ï¿½[ï¿½gï¿½Ê’u.
    Vector2 leftStartTouch = new Vector2();
    // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½^ï¿½bï¿½`ï¿½ï¿½ï¿½ï¿½.
    Vector2 leftTouchInput = new Vector2();

    // Start is called before the first frame update
    void Start()
    {
        // Animatorï¿½ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½ÛŠï¿½.
        animator = GetComponent<Animator>();
        // Rigidbodyï¿½Ìæ“¾.
        rigid = GetComponent<Rigidbody>();
        // ï¿½Uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½pï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½.
        attackHit.SetActive(false);

        // FootSphereï¿½ÌƒCï¿½xï¿½ï¿½ï¿½gï¿½oï¿½^.
        footColliderCall.TriggerStayEvent.AddListener(OnFootTriggerStay);
        footColliderCall.TriggerExitEvent.AddListener(OnFootTriggerExit);

        // ï¿½Uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½pï¿½Rï¿½ï¿½ï¿½Cï¿½_ï¿½[ï¿½Cï¿½xï¿½ï¿½ï¿½gï¿½oï¿½^.
        attackHitCall.TriggerEnterEvent.AddListener(OnAttackHitTriggerEnter);
        // ï¿½ï¿½ï¿½İ‚ÌƒXï¿½eï¿½[ï¿½^ï¿½Xï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½.
        CurrentStatus.Hp = DefaultStatus.Hp;
        CurrentStatus.Power = DefaultStatus.Power;

        // ï¿½Jï¿½nï¿½ï¿½ï¿½ÌˆÊ’uï¿½ï¿½]ï¿½ï¿½ÛŠï¿½.
        startPosition = this.transform.position;
        startRotation = this.transform.rotation;

        // ï¿½Xï¿½ï¿½ï¿½Cï¿½_ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½.
        hpBar.maxValue = DefaultStatus.Hp;
        hpBar.value = CurrentStatus.Hp;
    }

    // Update is called once per frame
    void Update()
    {
        // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ÉŒï¿½ï¿½ï¿½ï¿½ï¿½. 
        cameraController.UpdateCameraLook(this.transform);

        if (Application.platform == RuntimePlatform.Android || Application.platform == RuntimePlatform.IPhonePlayer)
        {
            // ï¿½Xï¿½}ï¿½zï¿½^ï¿½bï¿½`ï¿½ï¿½ï¿½ï¿½.
            // ï¿½^ï¿½bï¿½`ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½wï¿½Ìï¿½ï¿½ï¿½ï¿½Oï¿½ï¿½è‘½ï¿½ï¿½.
            if(Input.touchCount > 0)
            {
                isTouch = true;
                // ï¿½^ï¿½bï¿½`ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½×‚Äæ“¾.
                Touch[] touches = Input.touches;
                // ï¿½Sï¿½ï¿½ï¿½Ìƒ^ï¿½bï¿½`ï¿½ï¿½ï¿½Jï¿½ï¿½Ô‚ï¿½ï¿½Ä”ï¿½ï¿½ï¿½.
                foreach (var touch in touches)
                {
                    bool isLeftTouch = false;
                    bool isRightTouch = false;
                    // ï¿½^ï¿½bï¿½`ï¿½Ê’uï¿½ï¿½Xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½Nï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½.
                    if(touch.position.x > 0 && touch.position.x < Screen.width / 2)
                    {
                        isLeftTouch = true;

                    }
                    // ï¿½^ï¿½bï¿½`ï¿½Ê’uï¿½ï¿½Xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½Nï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Ì‰Eï¿½ï¿½.
                    else if (touch.position.x > Screen.width / 2 && touch.position.x < Screen.width)
                    {
                        isRightTouch = true; ;
                    }

                    // ï¿½ï¿½ï¿½^ï¿½bï¿½`.
                    if (isLeftTouch == true)
                    {
                        // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½^ï¿½bï¿½`ï¿½ï¿½ï¿½ï¿½ï¿½Û‚Ìï¿½ï¿½ï¿½.
                        // ï¿½^ï¿½bï¿½`ï¿½Jï¿½n.
                        if (touch.phase == TouchPhase.Began)
                        {
                            Debug.log("ã‚¿ãƒƒãƒé–‹å§‹");
                            // ï¿½Jï¿½nï¿½Ê’uï¿½ï¿½ÛŠï¿½.
                            leftStartTouch = touch.position;
                            // ï¿½Jï¿½nï¿½Ê’uï¿½Éƒ}ï¿½[ï¿½Jï¿½[ï¿½ï¿½\ï¿½ï¿½.
                            touchMarker.SetActive(true);
                            Vector3 touchPosition = touch.position;
                            touchPosition.z = 1f;
                            Vector3 markerPosition = Camera.main.ScreenToWorldPoint(touchPosition);
                            touchMarker.transform.position = markerPosition;
                        }
                        // ï¿½^ï¿½bï¿½`ï¿½ï¿½.
                        else if (touch.phase == TouchPhase.Moved || touch.phase == TouchPhase.Stationary)
                        {
                            Debug.log("ã‚¿ãƒƒãƒä¸­");
                            // ï¿½ï¿½ï¿½İ‚ÌˆÊ’uï¿½ğï¿½ï¿½
                            Vector2 position = touch.position;
                            // ï¿½Ú“ï¿½ï¿½pï¿½Ì•ï¿½ï¿½ï¿½ï¿½ï¿½ÛŠï¿½.
                            leftTouchInput = position - leftStartTouch;
                        }
                        // ï¿½^ï¿½bï¿½`ï¿½Iï¿½ï¿½.
                        else if (touch.phase == TouchPhase.Ended)
                        {
                            leftTouchInput = Vector2.zero;
                            // ï¿½}ï¿½[ï¿½Jï¿½[ï¿½ï¿½ï¿½\ï¿½ï¿½.
                            touchMarker.gameObject.SetActive(false);
                        }
                    }

                    // ï¿½Eï¿½^ï¿½bï¿½`.
                    if (isRightTouch == true)
                    {
                        // ï¿½Eï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½^ï¿½bï¿½`ï¿½ï¿½ï¿½ï¿½ï¿½Û‚Ìï¿½ï¿½ï¿½.
                        cameraController.UpdateRightTouch(touch);
                    }
                }

            }
            else
            {
                isTouch = false;
            }
        }
        else
        {
            // PCï¿½Lï¿½[ï¿½ï¿½ï¿½Íæ“¾.
            horizontalKeyInput = Input.GetAxis("Horizontal");
            verticalKeyInput = Input.GetAxis("Vertical");
        }

        // ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ÌŒï¿½ï¿½ï¿½ï¿½ğ’²ï¿½.
        bool isKeyInput = (horizontalKeyInput != 0 || verticalKeyInput != 0 || leftTouchInput != Vector2.zero);
        if (isKeyInput == true && isAttack == false)
        {
            bool currentIsRun = animator.GetBool("isRun");
            if (currentIsRun == false) animator.SetBool("isRun", true);
            Vector3 dir = rigid.velocity.normalized;
            dir.y = 0;
            this.transform.forward = dir;
        }
        else
            {
                bool currentIsRun = animator.GetBool("isRun");
                if (currentIsRun == true) animator.SetBool("isRun", false);
            }
        }

    void FixedUpdate()
    {
        // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ÌˆÊ’uï¿½ï¿½ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Éï¿½ï¿½í‚¹ï¿½ï¿½.
        cameraController.FixedUpdateCameraPosition(this.transform);

        if (isAttack == false)
        {
            Vector3 input = new Vector3();
            Vector3 move = new Vector3();
            if (Application.platform == RuntimePlatform.Android || Application.platform == RuntimePlatform.IPhonePlayer)
            {
                input = new Vector3(leftTouchInput.x, 0, leftTouchInput.y);
                move = input.normalized * 2f;
            }
            else
            {
                input = new Vector3(horizontalKeyInput, 0, verticalKeyInput);
                move = input.normalized * 2f;
            }
            Vector3 cameraMove = Camera.main.gameObject.transform.rotation * move;
            cameraMove.y = 0;
            Vector3 currentRigidVelocity = rigid.velocity;
            currentRigidVelocity.y = 0;

            rigid.AddForce(cameraMove - currentRigidVelocity, ForceMode.VelocityChange);
        }
    }

    // ---------------------------------------------------------------------
    /// <summary>
    /// ï¿½ñ•œï¿½ï¿½ï¿½.
    /// </summary>
    /// <param name="healPoint"> ï¿½ñ•œ—ï¿½. </param>
    // ---------------------------------------------------------------------
    public void OnHeal(int healPoint)
    {
        CurrentStatus.Hp += healPoint;
        Debug.Log("HPï¿½ï¿½" + healPoint + "ï¿½ï¿½!!");

        if (CurrentStatus.Hp > DefaultStatus.Hp) CurrentStatus.Hp = DefaultStatus.Hp;

        hpBar.value = CurrentStatus.Hp;
    }

    // ---------------------------------------------------------------------
    /// <summary>
    /// ï¿½Uï¿½ï¿½ï¿½{ï¿½^ï¿½ï¿½ï¿½Nï¿½ï¿½ï¿½bï¿½Nï¿½Rï¿½[ï¿½ï¿½ï¿½oï¿½bï¿½N.
    /// </summary>
    // ---------------------------------------------------------------------
    public void OnAttackButtonClicked()
    {
        if (isAttack == false)
        {
            // Animationï¿½ï¿½isAttackï¿½gï¿½ï¿½ï¿½Kï¿½[ï¿½ï¿½ï¿½Nï¿½ï¿½.
            animator.SetTrigger("isAttack");
            // ï¿½Uï¿½ï¿½ï¿½Jï¿½n.
            isAttack = true;
        }
    }

    // ---------------------------------------------------------------------
    /// <summary>
    /// ï¿½Uï¿½ï¿½ï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½Hitï¿½Cï¿½xï¿½ï¿½ï¿½gï¿½Rï¿½[ï¿½ï¿½.
    /// </summary>
    // ---------------------------------------------------------------------
    void Anim_AttackHit()
    {
        Debug.Log("Hit");
        // ï¿½Uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½pï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½\ï¿½ï¿½.
        attackHit.SetActive(true);
    }

    // ---------------------------------------------------------------------
    /// <summary>
    /// ï¿½Uï¿½ï¿½ï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½Cï¿½xï¿½ï¿½ï¿½gï¿½Rï¿½[ï¿½ï¿½.
    /// </summary>
    // ---------------------------------------------------------------------
    void Anim_AttackEnd()
    {
        Debug.Log("End");
        // ï¿½Uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½pï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½.
        attackHit.SetActive(false);
        // ï¿½Uï¿½ï¿½ï¿½Iï¿½ï¿½.
        isAttack = false;
    }

    // ---------------------------------------------------------------------
    /// <summary>
    /// ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½{ï¿½^ï¿½ï¿½ï¿½Nï¿½ï¿½ï¿½bï¿½Nï¿½Rï¿½[ï¿½ï¿½ï¿½oï¿½bï¿½N.
    /// </summary>
    // ---------------------------------------------------------------------
    public void OnJumpButtonClicked()
    {
        if (isGround == true)
        {
            Debug.Log("ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½v");
            rigid.AddForce(Vector3.up * jumpPower, ForceMode.Impulse);
        }
    }

    // ---------------------------------------------------------------------
    /// <summary>
    /// FootSphereï¿½gï¿½ï¿½ï¿½Kï¿½[ï¿½Xï¿½eï¿½Cï¿½Rï¿½[ï¿½ï¿½.
    /// </summary>
    /// <param name="col"> ï¿½Nï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Rï¿½ï¿½ï¿½Cï¿½_ï¿½[. </param>
    // ---------------------------------------------------------------------
    void OnFootTriggerStay(Collider col)
    {
        if (col.gameObject.tag == "Ground")
        {
            if (isGround == false) isGround = true;
            if (animator.GetBool("isGround") == false) animator.SetBool("isGround", true);
        }
    }

    // ---------------------------------------------------------------------
    /// <summary>
    /// FootSphereï¿½gï¿½ï¿½ï¿½Kï¿½[ï¿½Cï¿½Oï¿½Wï¿½bï¿½gï¿½Rï¿½[ï¿½ï¿½.
    /// </summary>
    /// <param name="col"> ï¿½Nï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Rï¿½ï¿½ï¿½Cï¿½_ï¿½[. </param>
    // ---------------------------------------------------------------------
    void OnFootTriggerExit(Collider col)
    {
        if (col.gameObject.tag == "Ground")
        {
            isGround = false;
            animator.SetBool("isGround", false);
        }
    }

    // ---------------------------------------------------------------------
    /// <summary>
    /// ï¿½Uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½gï¿½ï¿½ï¿½Kï¿½[ï¿½Gï¿½ï¿½ï¿½^ï¿½[ï¿½Cï¿½xï¿½ï¿½ï¿½gï¿½Rï¿½[ï¿½ï¿½.
    /// </summary>
    /// <param name="col"> ï¿½Nï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Rï¿½ï¿½ï¿½Cï¿½_ï¿½[. </param>
    // ---------------------------------------------------------------------
    void OnAttackHitTriggerEnter(Collider col)
    {
        if (col.gameObject.tag == "Enemy")
        {
            var enemy = col.gameObject.GetComponent<EnemyBase>();
            enemy?.OnAttackHit(CurrentStatus.Power, this.transform.position);
            attackHit.SetActive(false);
        }
    }

// ---------------------------------------------------------------------
    /// <summary>
    /// ï¿½Gï¿½ÌUï¿½ï¿½ï¿½ï¿½ï¿½qï¿½bï¿½gï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½Ìï¿½ï¿½ï¿½.
    /// </summary>
    /// <param name="damage"> ï¿½Hï¿½ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½[ï¿½W. </param>
    // ---------------------------------------------------------------------
    public void OnEnemyAttackHit( int damage, Vector3 attackPosition )
    {
        CurrentStatus.Hp -= damage;
        hpBar.value = CurrentStatus.Hp;

        var pos = myCollider.ClosestPoint( attackPosition );
        var obj = Instantiate( hitParticlePrefab, pos, Quaternion.identity );
        var par = obj.GetComponent<ParticleSystem>();
        StartCoroutine( WaitDestroy( par ) );
        particleObjectList.Add(obj);

        if ( CurrentStatus.Hp <= 0 )
        {
            OnDie();
        }
        else
        {
            Debug.Log( damage + "ï¿½Ìƒ_ï¿½ï¿½ï¿½[ï¿½Wï¿½ï¿½Hï¿½ï¿½ï¿½ï¿½ï¿½!!ï¿½cï¿½ï¿½HP" + CurrentStatus.Hp );
        }
    }
 
ï¿½@ï¿½@// ---------------------------------------------------------------------
    /// <summary>
    /// ï¿½pï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½jï¿½ï¿½ï¿½ï¿½ï¿½ï¿½.
    /// </summary>
    /// <param name="particle"></param>
    // ---------------------------------------------------------------------
    IEnumerator WaitDestroy( ParticleSystem particle )
    {
        yield return new WaitUntil( () => particle.isPlaying == false );
        if (particleObjectList.Contains(particle.gameObject) == true) particleObjectList.Remove(particle.gameObject);
        Destroy( particle.gameObject );
    }

    // ---------------------------------------------------------------------
    /// <summary>
    /// ï¿½ï¿½ï¿½Sï¿½ï¿½ï¿½ï¿½ï¿½ï¿½.
    /// </summary>
    // ---------------------------------------------------------------------
    void OnDie()
    {
        Debug.Log("ï¿½ï¿½ï¿½Sï¿½ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½ï¿½B");
        StopAllCoroutines();
        if (particleObjectList.Count > 0)
        {
            foreach (var obj in particleObjectList) Destroy(obj);
            particleObjectList.Clear();
        }
        GameOverEvent?.Invoke();
    }

    // ---------------------------------------------------------------------
    /// <summary>
    /// ï¿½ï¿½ï¿½gï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½ï¿½.
    /// </summary>
    // ---------------------------------------------------------------------
    public void Retry()
    {
        // ï¿½ï¿½ï¿½İ‚ÌƒXï¿½eï¿½[ï¿½^ï¿½Xï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½.
        CurrentStatus.Hp = DefaultStatus.Hp;
        CurrentStatus.Power = DefaultStatus.Power;
        hpBar.value = CurrentStatus.Hp;

        // ï¿½Ê’uï¿½ï¿½]ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ê’uï¿½É–ß‚ï¿½.
        this.transform.position = startPosition;
        this.transform.rotation = startRotation;

        //ï¿½Uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì“rï¿½ï¿½ï¿½Å‚ï¿½ï¿½ê‚½ï¿½ï¿½ï¿½p
        isAttack = false;

    }

}