using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerCameraController : MonoBehaviour
{
    [SerializeField] Transform rotationRoot = null;
    // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½pï¿½gï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½tï¿½Hï¿½[ï¿½ï¿½.
    [SerializeField] Transform heightRoot = null;
    // ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Jï¿½ï¿½ï¿½ï¿½.
    [SerializeField] Camera mainCamera = null;

    // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ê‚ï¿½ï¿½ï¿½ï¿½Sï¿½Ìƒvï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ç‚ï¿½ï¿½.
    [SerializeField] float lookHeight = 1.0f;
    // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ï¿½]ï¿½Xï¿½sï¿½[ï¿½h.
    [SerializeField] float rotationSpeed = 0.01f;
    // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ï‰ï¿½ï¿½Xï¿½sï¿½[ï¿½h.
    [SerializeField] float heightSpeed = 0.001f;
    // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½MinMax.
    [SerializeField] Vector2 heightLimit_MinMax = new Vector2(-1f, 3f);

    // ï¿½^ï¿½bï¿½`ï¿½Xï¿½^ï¿½[ï¿½gï¿½Ê’u.
    Vector2 cameraStartTouch = Vector2.zero;
    // ï¿½ï¿½ï¿½Ý‚Ìƒ^ï¿½bï¿½`ï¿½Ê’u.
    Vector2 cameraTouchInput = Vector2.zero;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public void UpdateCameraLook(Transform player)
    {
        // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ÉŒÅ’ï¿½.
        var cameraMarker = player.position;
        cameraMarker.y += lookHeight;
        var _camLook = (cameraMarker - mainCamera.transform.position).normalized;
        mainCamera.transform.forward = _camLook;
    }

    public void FixedUpdateCameraPosition(Transform player)
    {
        this.transform.position = player.position;
    }

    public void UpdateRightTouch(Touch touch)
    {
        // ï¿½^ï¿½bï¿½`ï¿½Jï¿½n.
        if (touch.phase == TouchPhase.Began)
        {
            Debug.Log("ï¿½Eï¿½^ï¿½bï¿½`ï¿½Jï¿½n");
            // ï¿½Jï¿½nï¿½Ê’uï¿½ï¿½ÛŠï¿½.
            cameraStartTouch = touch.position;
        }
        // ï¿½^ï¿½bï¿½`ï¿½ï¿½.
        else if (touch.phase == TouchPhase.Moved || touch.phase == TouchPhase.Stationary)
        {
            Debug.Log("ï¿½Eï¿½^ï¿½bï¿½`ï¿½ï¿½");
            // ï¿½ï¿½ï¿½Ý‚ÌˆÊ’uï¿½ðŽï¿½ï¿½ÛŠï¿½.
            Vector2 position = touch.position;
            // ï¿½Jï¿½nï¿½Ê’uï¿½ï¿½ï¿½ï¿½ÌˆÚ“ï¿½ï¿½xï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½ï¿½Zï¿½o.
            cameraTouchInput = position - cameraStartTouch;
            // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ï¿½].
            var yRot = new Vector3(0, cameraTouchInput.x * rotationSpeed, 0);
            var rResult = rotationRoot.rotation.eulerAngles + yRot;
            var qua = Quaternion.Euler(rResult);
            rotationRoot.rotation = qua;

            // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½.
            var yHeight = new Vector3(0, -cameraTouchInput.y * heightSpeed, 0);
            var hResult = heightRoot.transform.localPosition + yHeight;
            if (hResult.y > heightLimit_MinMax.y) hResult.y = heightLimit_MinMax.y;
            else if (hResult.y <= heightLimit_MinMax.x) hResult.y = heightLimit_MinMax.x;
            heightRoot.localPosition = hResult;
        }
        // ï¿½^ï¿½bï¿½`ï¿½Iï¿½ï¿½.
        else if (touch.phase == TouchPhase.Ended)
        {
            Debug.Log("ï¿½Eï¿½^ï¿½bï¿½`ï¿½Iï¿½ï¿½");
            cameraTouchInput = Vector2.zero;
        }
    }
}
